Add K3S info to orchestration
owncloud/docs-ocis pull request #1090
Opened 2024-12-10 10:30 UTC by mmattel

Fixes: #716 (Document how to configure K3S to resolve custom domains to the host)

Just a small docs addon to orchestration.

No backport

2024-12-10 13:14 UTC, phil-davis commented on modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
> +CoreDNS needs to know how to resolve domains like `ocis.kube.owncloud.test` to the host, like `raspbian-bullseye-arm64`. To authenticate users via OIDC, the proxy service has to be able to resolve th
```suggestion
CoreDNS needs to know how to resolve domains like `ocis.kube.owncloud.test` to the host, like `raspbian-bullseye-arm64`. To authenticate users via OIDC, the proxy service has to be able to resolve the `externalDomain:ocis.kube.owncloud.test`.
```

2024-12-12 10:26 UTC, kobergj requested changes
Missing `e`

2024-12-12 10:26 UTC, kobergj commented on modules/ROOT/pages/deployment/container/orchestration/orchestration.adoc
> +Since all `*.kube.owncloud.test` domains should point to the host, the CorDNS rewrite plugin can be used like the following:
```suggestion
Since all `*.kube.owncloud.test` domains should point to the host, the CoreDNS rewrite plugin can be used like the following:
```

2024-12-12 10:27 UTC, kobergj approved these changes

2024-12-12 10:28 UTC, merged